name: CI/CD test

on:
  pull_request:
    branches:
      - main

jobs:
  integration-test:
    runs-on: ubuntu-latest
    services:
      mysql:
        image: mysql:latest
        env:
          MYSQL_ROOT_PASSWORD: ${{ secrets.DB_ROOT_PASSWORD }}
          MYSQL_DATABASE: ${{ secrets.DB_DATABASE }}
          MYSQL_USER: ${{ secrets.DB_USER }}
          MYSQL_HOST: ${{ secrets.DB_HOST }}
          MYSQL_PASSWORD: ${{ secrets.DB_ROOT_PASSWORD }}
        ports:
          - 3306:3306
        options: --health-cmd="mysqladmin ping" --health-interval=10s --health-timeout=5s --health-retries=3
    steps:
      - name: Checkout Code
        uses: actions/checkout@v2

      - name: Set up Go
        uses: actions/setup-go@v2
        with:
          go-version: 1.21.2

      - name: Wait for MySQL to be ready
        run: |
          until nc -z -v -w30 ${{ secrets.DB_HOST }} ${{ secrets.DB_PORT }}
          do
            echo "Waiting for MySQL to be ready..."
            sleep 5
          done

      - name: Install project dependencies
        run: |
          go get -d -v ./...
          go build -v

      - name: Run Integration tests
        run: |
          DB_HOST=${{ secrets.DB_HOST }} 
          DB_PORT=${{ secrets.DB_PORT }} 
          DB_USER=${{ secrets.DB_USER }} 
          DB_PASSWORD=${{ secrets.DB_ROOT_PASSWORD }} 
          DB_NAME=${{ secrets.DB_DATABASE }} 
          go test ./...
